activate script now takes -e flag for environment

diff --git a/activate b/activate
--- a/activate
+++ b/activate
@@ -1,5 +1,56 @@
 #!/bin/bash
 . $HOME/repositories/cliquesadmin/venv/bin/activate
+
+# usage text visible when --help flag passed in
+usage="activate-- Activate specific envioronment, setting all necessary environment variables.
+
+where:
+    -e      environment name (e.g. 'dev', 'production').  Default is 'production'
+    --help  show this help text
+
+example:
+    # activates the 'dev' environment
+    $ source activate.sh -e dev
+"
+
+OPTIND=1
+######### BEGIN environment parsing ########
+# Default to production
+env="production"
+
+if [ ! -z $2 ]; then
+  if [ $2 == '--help' ]; then
+    echo "$usage"
+    return  0
+  fi
+fi
+
+# fucking getopts
+while getopts ":e:" opt; do
+  case $opt in
+    e)
+      if [ "$OPTARG" != 'production' ] && [ "$OPTARG" != 'dev' ]; then
+        echo "Invalid environment: $OPTARG.  Environment must be either 'dev' or 'production'"
+        return 1
+      else
+        env="$OPTARG"
+      fi
+      ;;
+    \?)
+      echo "Invalid option: -$OPTARG" >&2
+      echo "$usage"
+      return 1
+      ;;
+    :)
+      echo "Environment flag -$OPTARG requires an argument (either 'dev' or 'production')" >&2
+      return 1
+      ;;
+  esac
+done
+
+# now set NODE_ENV to env, setting NODE_ENV environment variable for subsequent scripts
+echo "Setting ENV=$env"
+
 PYTHONPATH=$HOME'/repositories/cliquesadmin'
 export PYTHONPATH
-export ENV=production
+export ENV="$env"
